# Generated by Django 2.2.3 on 2019-07-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('source', models.CharField(max_length=250)),
                ('data', models.FloatField()),
            ],
        ),
    ]
