# Generated by Django 2.2.3 on 2019-07-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTD', '0002_auto_20190715_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy',
            name='time_string',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
